name: 编译客户端

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-app.yaml'
      - 'client/**'

concurrency:
  group: "client"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:

    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        sudo apt install -y libdbus-1-dev \
          libsoup3.0-dev \
          libjavascriptcoregtk-4.1-dev \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          gnome-video-effects \
          gnome-video-effects-extra

    - name: 配置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    
    - name: 安装 Pake
      run: |
        npm install -g pake-cli && pake --version
    
    - name: 编译客户端
      run: |
        YAA_VERSION=$(grep '^version' ./Cargo.toml | awk -F= '{print $2}' | tr -d '" ')
        mkdir -p target && mkdir -p target/client
        cd target/client
        pake ../../client/index.html \
          -name yaa \
          --icon ../../assets/yaa_512.png \
          --installer-language zh-CN \
          --app-version $YAA_VERSION \
          --use-local-file
        cd ../..

    - name: 上传包
      uses: actions/upload-artifact@v4
      with:
        path: 'target/client/*/*.*'