name: 部署文档到 GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:

    - name: 检出仓库
      uses: actions/checkout@v4
    
    - name: 部署 markdown.html
      uses: PJ-568/MARKDOWN.HTML@v1.9.0
      with:
        target-dir: 'docs'

    - name: 配置 Pages
      uses: actions/configure-pages@v4

    - name: 上传 Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs'

    - name: 部署到 GitHub Pages
      id: deploy-docs
      uses: actions/deploy-pages@v4